---
- hosts: localhost
  become: true
  tasks:
    - name: Install required system packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - neovim
        state: latest
        update_cache: yes

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes

    - name: Add user to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Download Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Ensure Docker Compose is executable
      file:
        path: /usr/local/bin/docker-compose
        mode: '0755'
        state: file

          #- name: Install OpenSSL
          #  apt:
          #    name: openssl
          #    state: present

    - name: add certbot
      ansible.builtin.command: sudo snap install --classic certbot && sudo ln -s /snap/bin/certbot /usr/bin/certbot


    - name: add scrit to run at boot
      ansible.builtin.copy:
        dest: /usr/local/bin/run_at_boot.sh
        content: |
          #!/bin/bash
          echo "this was runned at boot ${date}" >> /var/log/my_data.log
          cd /home/ubuntu/cloud-1 && docker compose up -d
        mode: 0755

    - name: setup cron job to launch script on reboot
      ansible.builtin.cron:
        name: "Run script at boot"
        special_time: reboot
        job: "/usr/local/bin/run_at_boot.sh"
        user: root


    - name: add .env variables to bashrc and source bashrc
      ansible.builtin.command: |
        echo 'export $(xargs </home/ubuntu/cloud-1/.env)' >> ~/.bashrc && source ~/.bashrc

    - name: Install step-ca
      ansible.builtin.command: |
          wget https://dl.smallstep.com/cli/docs-cli-install/latest/step-cli_amd64.deb && sudo dpkg -i step-cli_amd64.deb 

    - name: run script
      ansible.builtin.command: sudo sh /usr/local/bin/run_at_boot.sh
