version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "your_password"
      MYSQL_DATABASE: wordpress

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./uploads:/var/www/html/wp-content/uploads

volumes:
  wp-content:
  uploads:

