---
- hosts: localhost
  become: true
  tasks:

    - name: Install OpenSSL
      apt:
        name: openssl
        state: present

    - name: Generate an OpenSSL private key
      openssl_privatekey:
        path: /etc/ssl/private/ansible.pem

    - name: Generate an OpenSSL CSR
      openssl_csr:
        path: /etc/ssl/private/ansible.csr
        privatekey_path: /etc/ssl/private/ansible.pem
        common_name: test_domain_cloud1.com

    - name: Generate a Self Signed OpenSSL certificate
      openssl_certificate:
        path: /etc/ssl/certs/ansible.crt
        privatekey_path: /etc/ssl/private/ansible.pem
        csr_path: /etc/ssl/private/ansible.csr
        provider: selfsigned

    - name: Copy the certificate and private key to your applications
      copy:
        src: /etc/ssl/certs/ansible.crt
        dest: /home/ubuntu/cloud-1/certs/certificate.crt

    - name: Copy the private key to your applications
      copy:
        src: /etc/ssl/private/ansible.pem
        dest: /home/ubuntu/cloud-1/certs/private_cert.pem 
